name: pantheriniidmaybeapp
description: Maybe you can identify Pantherini species.
version: 3.0.0+3

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  pedantic_mono: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
